version: '3.8'

services:
#   app:
#     build: .
#     container_name: top_five
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgres://postgres:postgres@db:5432/database
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
